name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release Version"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Publish to Maven Central
        run: ./gradlew clean build bintrayUpload -PbintrayUser=${BINTRAY_USER} -PbintrayKey=${BINTRAY_KEY} -PdryRun=false
        env:
         RELEASE_VERSION: ${{ github.event.inputs.version }}
         BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
         BINTRAY_USER: ${{ secrets.BINTRAY_USER }}